apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: {{ .Values.sonarqube.service.port }}
      targetPort: 9000
  type: {{ .Values.sonarqube.service.type }}
